// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// The anon/publishable key is safe to embed in client apps — row level
// security on the backend governs access. These fallbacks keep the app
// working when VITE_SUPABASE_* env vars are not provided at build time.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? 'https://nhalxqobrsuuzmmefeid.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oYWx4cW9icnN1dXptbWVmZWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMzYxNTMsImV4cCI6MjA5MDcxMjE1M30.JTMv2pWaLurqc-aCUNPkEReW1lImL6IlIpRe0k4SH0E';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});